### PR TITLE
adding vocabularies

### PR DESCRIPTION
**Pull request by jverweijL**
just a skeleton for the vocabularies, no logic yet

### CODE REVIEW

**Comment by jverweijL** [comment]
not fully ready but starting point

**Comment by jverweijL** [comment]
added creating root categories.. subcategories will follow tomorrow

**Comment by jverweijL** [comment]
basic stuff is working not to clean some code

**Comment by jverweijL** [comment]
cleansing code

**Review by mahmoudhtayem87 — APPROVED** [review]

**Pull request merged**
